### ISSUE TITLE
Developer experience audit from @mntnr

### ISSUE THREAD

**Issue by RichardLitt** [probot/probot.github.io#180]
:wave: Hey there! This is the developer experience audit from @mntnr for this repository. I've added in my thoughts below, in the form of a checklist. Looking forward to seeing what you think; let's see if we can resolve all of the open issues and make this repository shine ✨ 💖 ✨

# Repository Review: probot/probot.github.io

> This is the home of probot documentation, apps, how-to guides and more.

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose. If I think that something is fine, even if it isn't valid according to this checklist, I've checked it off and included a note._

### Reviewing the Repository Docs

- [x] Is there a README?
  - [ ] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)? _More or less_
  - [x] Is it spellchecked?
- [x] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [x] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [x] Does it reference an email address for violations?
- [x] Is there a `LICENSE` file?
  - [ ] Is the year correct? _There's no year or attribution in the file. I'm not sure if that's Ok. Ask your lawyer._
- [x] Is there a `.github` or `docs` folder?
  - [ ] Is there an `ISSUE_TEMPLATE.md`?
  - [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?
- [x] Is there a `CONTRIBUTING.md` file?
  - [x] Does it mention how to make a PR?
  - [~] Does it mention what sort of issues you'd like?
  - [~] Does it mention a `good first issue` label as a starting point?
  - [ ] Does it mention triaging and bug reports as good starting points? _I think this is OK for this repo._
  - [~] Does it point to a community chat program, like Slack or Gitter?
  - [~] Does it encourage conversations in issues before opening huge PRs?
  - [~] Does it specify where to ask questions on process?
  - [~] Does it explain labels used in the issues?
- [ ] Is there a `CHANGELOG`? _Probably not necessary for this repo.)
  - [ ] If there isn't, are notes included in the project's releases?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
- [x] Does the repository name itself pass on http://wordsafety.com?

### Process
- [~] Can I install easily? _I included some directions in the README, and edited the scripts in the `script` folder to make this easier.
- [~] Can I use this easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests?
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old?
- [x] Are there useful issue labels?
- [x] Are the labels being used? _Could be better, though_
- [x] Is there a `good for beginners` or `good first issue` label?
- [ ] Is there a `waiting on contributor` label? _Might be useful_

### Bots

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [x] Are there bots enabled? _Stalebot_
- [~] Are the bots listed in the Contribute or Readme files so that users can expect to interact with them?

### Metadata
- [x] Is there a description on GitHub?
  - [ ] Does the description match the README? _No, it doesn't. I think that the one in the README is better, because it makes it clear that this is for the website. I would update it on GitHub to: "This is the home of probot.github.io, a website for [probot](https://github.com/probot/probot) documentation, apps, how-to guides and more."_
- [x] Are the topics useful?
- [x] Is there a website?
  - [x] Does the website match the project?

### TODO

This is generally pretty good! I've added a PR and gone through and fixed the salient issues. I don't think this needs much more scrubbing at the moment. 

#### Generic
- [ ] Add a link to your Slack! You want to engage with users there.
- [ ] Consider adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to your repository. It looks like you have your PRs well under control, but these may help you in the future. At the least, ask them to run the tests, first, and to read the Usage guides.
- [ ] This audit does _not_ cover license dependency. For that, I suggest using either [licensee](https://github.com/jslicense/licensee.js) or an external tool like [Fossa](https://fossa.io/). Let me know if you want more help here.

#### Issues
- [ ] Considering adding `available` labels as well as `good first issue` and `help wanted`. These can be used to signal that you're looking for community involvement for issues. They can also be configured to display on http://up-for-grabs.net. This will help more people interact with your code, and lead to small, iterative work done by others. It may take some time to set up initially - properly scoping issues for newcomers takes some time - but the payback should be worth it.
- [ ] I label pull requests where I am waiting on the Contributor to respond `waiting on contributor`. This helps alleviate pressure on you to close them.

## Contribute back?

This checklist is open source! If you have suggestions or think it could be better, contribute back on [mntnr/audit-templates](https://github.com/mntnr/audit-templates).

Thank you!

**Comment by RichardLitt** [comment]
Thank you, @hiimbex!
